excluded:
  - Fastlane/SnapshotHelper.swift
  - Shared/Extensions/String+Levenshtein.swift

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - colon
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - nimble_operator
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

identifier_name:
  excluded:
    - a
    - b
    - i
    - j
    - to
    - id
    - cs
    - uk
    - pl
    - sk
    - t1
    - t2
  allowed_symbols: "_"
