# Checks if the project can be built and runs tests
name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check_build:
    runs-on: macos-12
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          bundle install
          bundle exec fastlane build

  tests:
    runs-on: macos-12
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
      APP_STORE_API_KEY: ${{ secrets.APP_STORE_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Build & Upload
        run: |
          bundle install
          bundle exec fastlane tests
