name: Data update

on:
  workflow_dispatch:

jobs:
  DataUpdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: DataUpdate
        run: ruby update-data.rb

      - name: Install ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.3.22
          bundler-cache: true

      - name: Update CHANGELOG.md
        run: |
          bundle install
          bundle exec fastlane update_changelog_data_update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'Update data to latest version (from movapp-data repository)'
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: data-update
          base: main
          delete-branch: true
          title: 'Update data to latest version (from movapp-data repository)'
          reviewers: kubito,pionl
