name: Data update
description: Fetches new data from movapp-data. Triggered externally.

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - data-update

jobs:
  DataUpdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: DataUpdate
        run: ruby update-data.rb

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          commit-message: 'Update data to latest version (from movapp-data repository)'
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: data-update
          base: main
          delete-branch: true
          title: 'Update data to latest version (from movapp-data repository)'
          reviewers: kubito,pionl
