name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  app_store:
    runs-on: macos-latest
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
      APP_STORE_API_KEY: ${{ secrets.APP_STORE_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Build & Upload
        run: |
          bundle install
          bundle exec fastlane upload
