name: Precheck

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  precheck:
    runs-on: macos-12
    env:
      APP_STORE_API_KEY: ${{ secrets.APP_STORE_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: check metadata
        run: |
          bundle install
          bundle exec fastlane check_metadata
