# Release a new minor version
name: Release

on:
  workflow_dispatch:

concurrency:
  group: movapp-apple-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Tag new minor version
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
      - name: Run fastlane
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          bundle install
          bundle exec fastlane release
          git push origin --follow-tags
