# Deploys new version to app_store, generates screenshots and publish them on Github Pages.
name: TestPipeline

on:
  push:
  workflow_dispatch:

concurrency:
  group: movapp-apple-TestPipeline-${{ github.ref }}
  cancel-in-progress: true

jobs:
  screenshots:
    runs-on: macos-12
    timeout-minutes: 240
    steps:
      - uses: actions/checkout@v3
      - name: Build & Upload
        run: |
          bundle install
          bundle exec fastlane create_missing_devices
          bundle exec fastlane screenshots
