name: TestPipeline

on:
  workflow_dispatch:

concurrency:
  group: movapp-apple-test-pipeline-${{ github.ref }}
  cancel-in-progress: true

jobs:
  screenshots:
    runs-on: macos-12
    timeout-minutes: 240
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
      APP_STORE_API_KEY: ${{ secrets.APP_STORE_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Build & Upload
        run: |
          bundle install
          bundle exec fastlane create_missing_devices
